#!/usr/bin/env python3
"""Render the OneLife world as a vintage fantasy map (Middle-earth style):
layered PNGs + a coordinate metadata file + a legend.

It reads the YAML game-data (the same files the engine seeds), lays the places
out deterministically on a grid (so coordinates are exact), draws aged parchment,
ink coastline/forest/field terrain, hand-inked roads, a compass rose, a title
cartouche and a legend, and places a pen-and-ink icon per location (generated by
the free Pollinations image provider, cached, with a procedural fallback).

Output is a STACK of PNG layers so the game can reveal it place-by-place
(fog of war):
  base.png         always-on parchment canvas
  loc-<id>.png      one transparent tile per location  (icon + label + terrain)
  road-<id>.png     one transparent tile per road
  room-<nodeid>.png the school's interior nodes, drawn as rooms
  frame.png         border + compass + title + legend (always on top)
  world-map.meta.json   pixel positions of every place + road polygons + tile bboxes

Usage:
  python render_map.py [--out DIR] [--content DIR] [--no-ai] [--size WxH]
--content defaults to $GAME_DATA_DIR, then $CONTENT_DIR, then ../OneLife-KBK-mystery
--out defaults to ../../web/public/worldmap (relative to this script)
"""
import os
import sys
import io
import glob
import json
import math
import argparse
import hashlib
import urllib.parse
import urllib.request

try:
    import yaml
except ImportError:
    sys.exit("PyYAML is required: pip install pyyaml")
try:
    from PIL import Image, ImageDraw, ImageFont, ImageFilter, ImageOps, ImageChops
except ImportError:
    sys.exit("Pillow is required: pip install pillow")

LIST_KEYS = ["arcs", "cells", "characters", "locations", "nodes", "gates",
             "puzzles", "clues", "edges"]

# --- vintage palette (RGB) ------------------------------------------------- #
PARCH      = (224, 203, 158)
PARCH_DARK = (196, 170, 120)
INK        = (78, 54, 33)        # main brown ink
INK_SOFT   = (120, 95, 62)
WATER      = (120, 150, 158)
WATER_INK  = (86, 116, 128)
FOREST     = (104, 124, 78)
FIELD      = (205, 192, 138)
HILL       = (150, 128, 92)

HERE = os.path.dirname(os.path.abspath(__file__))


# --------------------------------------------------------------------------- #
#  Data
# --------------------------------------------------------------------------- #
def load_data(content_dir):
    data = {k: [] for k in LIST_KEYS}
    for f in sorted(glob.glob(os.path.join(content_dir, "*.yaml"))):
        with open(f, encoding="utf-8") as fh:
            doc = yaml.safe_load(fh) or {}
        for k in LIST_KEYS:
            data[k].extend(doc.get(k) or [])
    return data


def find_content_dir(explicit):
    for cand in (explicit, os.environ.get("GAME_DATA_DIR"),
                 os.environ.get("CONTENT_DIR"),
                 os.path.join(HERE, "..", "..", "..", "..", "OneLife-KBK-mystery")):
        if cand and os.path.isdir(cand) and glob.glob(os.path.join(cand, "*.yaml")):
            return os.path.abspath(cand)
    sys.exit("Could not find game-data dir (set GAME_DATA_DIR or pass --content).")


# --------------------------------------------------------------------------- #
#  Icon concept matching — keyword -> (concept id, pen-and-ink prompt subject)
# --------------------------------------------------------------------------- #
CONCEPTS = [
    (("school", "killeb", "classroom", "boiler", "pannrum", "entrance hall"),
     "school", "a small old schoolhouse building with a bell tower"),
    (("church", "churchyard", "chapel", "lych", "kyrk", "graveyard sloping"),
     "church", "a small medieval country church with a steeple and cross"),
    (("harbour", "harbor", "quay", "crane", "dock", "öresund", "oresund", "pier", "crossing"),
     "harbour", "a harbour with sailing ships, masts and dock cranes"),
    (("lake", "quarry", "gravel-pit", "gravel pit", "pond", "motel"),
     "lake", "a small lake with a little lakeside inn"),
    (("manor", "derelict manor"), "manor", "a grand derelict manor house"),
    (("castle", "fortress", "moat", "malmöhus", "malmohus"),
     "castle", "a moated castle fortress with round towers"),
    (("tower", "torso", "skyscraper"), "tower", "a tall twisting tower"),
    (("cemetery", "kyrkogård", "kyrkogard", "gravestone", "leaning stones", "old stones"),
     "cemetery", "rows of leaning old gravestones"),
    (("station", "train", "railway", "departures", "platform", "citytunnel", "triangeln", "tunnel"),
     "station", "a small old railway station with a clock"),
    (("library", "annex", "book"), "library", "an open book and a small library building"),
    (("cellar", "supper", "vault", "basement", "server"),
     "cellar", "a cellar entrance with stone stairs going down"),
    (("lodging", "rooms", "study", "clipping"), "lodgings", "a cramped town townhouse"),
    (("botanic", "glasshouse", "garden", "greenhouse"),
     "garden", "a Victorian glasshouse greenhouse with plants"),
    (("apothecary", "pharmacy", "jars"), "apothecary", "old apothecary jars and bottles"),
    (("crypt", "stone-crypt", "pillar"), "crypt", "a stone crypt archway underground"),
    (("square", "torget", "stortorget", "cathedral square", "cobble"),
     "square", "an open town square with a statue and fountain"),
    (("rosengård", "rosengard", "estate", "concrete tower", "cage pitch"),
     "estate", "tall concrete housing tower blocks"),
    (("police", "detective", "murder board"), "police", "an official town hall building with a flag"),
    (("park", "pildamm", "reeds", "lakeside park"), "park", "park trees beside a small pond"),
    (("crooked", "leaning house", "edge of"), "crooked", "a crooked leaning little house"),
    (("forest", "woods", "pine", "track", "trees"), "forest", "a dense cluster of pine forest trees"),
    (("street", "village", "main street", "lane"), "village", "a cluster of little village cottages"),
]


def concept_for(loc):
    text = ((loc.get("name") or "") + " " + (loc.get("description") or "")).lower()
    for kws, cid, subj in CONCEPTS:
        if any(k in text for k in kws):
            return cid, subj
    return "house", "a small lone cottage"


def _seed(s):
    return int(hashlib.md5(s.encode()).hexdigest()[:8], 16)


# --------------------------------------------------------------------------- #
#  Icons — Pollinations pen-and-ink, cached, ink-on-transparent. Fallback: shapes.
# --------------------------------------------------------------------------- #
def ink_from_white(rgb, color=INK):
    """White-background line art -> sepia ink on a transparent layer. Autocontrast
    first (so the lightest pixels become white), then drop near-white to fully
    transparent so only the inked lines remain (no muddy grey box)."""
    g = ImageOps.autocontrast(rgb.convert("L"), cutoff=1)
    cut = 198
    alpha = g.point(lambda L: 0 if L > cut else min(255, int(((cut - L) / cut) ** 0.8 * 300)))
    out = Image.new("RGBA", rgb.size, color + (0,))
    out.putalpha(alpha)
    return out


def procedural_icon(concept, size):
    """A crude but recognisable black-on-white doodle, used when AI is off/unreachable."""
    im = Image.new("RGB", (size, size), "white")
    d = ImageDraw.Draw(im)
    s = size
    w = max(3, s // 40)
    cx = s // 2
    def line(p, width=w): d.line(p, fill="black", width=width, joint="curve")
    if concept in ("forest", "park"):
        for i, x in enumerate((s*0.28, s*0.5, s*0.72)):
            top = s*(0.22 + 0.05*(i % 2)); base = s*0.82
            line([(x, top), (x, base)]);
            d.polygon([(x-s*0.13, base*0.78), (x, top), (x+s*0.13, base*0.78)], outline="black", width=w)
    elif concept == "church":
        d.rectangle([s*0.32, s*0.45, s*0.68, s*0.82], outline="black", width=w)
        d.polygon([(s*0.32, s*0.45), (s*0.5, s*0.28), (s*0.68, s*0.45)], outline="black", width=w)
        line([(s*0.5, s*0.1), (s*0.5, s*0.3)]); line([(s*0.42, s*0.18), (s*0.58, s*0.18)])
    elif concept in ("harbour",):
        line([(s*0.2, s*0.7), (s*0.8, s*0.7)])
        line([(s*0.5, s*0.2), (s*0.5, s*0.7)])
        d.polygon([(s*0.5, s*0.3), (s*0.74, s*0.55), (s*0.5, s*0.55)], outline="black", width=w)
        for y in (s*0.78, s*0.86): d.arc([s*0.2, y-12, s*0.4, y+12], 200, 340, fill="black", width=w)
    elif concept in ("lake", "park"):
        d.ellipse([s*0.2, s*0.45, s*0.8, s*0.72], outline="black", width=w)
    elif concept in ("castle",):
        d.rectangle([s*0.28, s*0.4, s*0.72, s*0.82], outline="black", width=w)
        for x in (0.28, 0.46, 0.62): d.rectangle([s*x, s*0.32, s*(x+0.1), s*0.42], outline="black", width=w)
    elif concept in ("tower",):
        d.rectangle([s*0.42, s*0.2, s*0.58, s*0.82], outline="black", width=w)
    elif concept in ("cemetery", "crypt"):
        for x in (0.3, 0.5, 0.7):
            d.rectangle([s*(x-0.07), s*0.5, s*(x+0.07), s*0.82], outline="black", width=w)
            d.arc([s*(x-0.07), s*0.43, s*(x+0.07), s*0.57], 180, 360, fill="black", width=w)
    elif concept in ("station",):
        d.rectangle([s*0.28, s*0.5, s*0.72, s*0.82], outline="black", width=w)
        d.line([(s*0.24, s*0.5), (s*0.76, s*0.5)], fill="black", width=w)
        d.ellipse([s*0.45, s*0.58, s*0.55, s*0.68], outline="black", width=w)
    else:  # house / village / manor / estate / generic
        d.rectangle([s*0.3, s*0.48, s*0.7, s*0.82], outline="black", width=w)
        d.polygon([(s*0.28, s*0.48), (s*0.5, s*0.3), (s*0.72, s*0.48)], outline="black", width=w)
        d.rectangle([s*0.44, s*0.62, s*0.56, s*0.82], outline="black", width=w)
    return im


def get_icon(concept, subject, cache_dir, use_ai, size=360):
    """Cache the RAW white-background art (so keying can be re-tuned without
    re-fetching); return it keyed to ink-on-transparent."""
    raw_path = os.path.join(cache_dir, f"{concept}.png")
    if os.path.exists(raw_path):
        try:
            return ink_from_white(Image.open(raw_path).convert("RGB"))
        except Exception:
            pass
    rgb = None
    if use_ai:
        prompt = (f"vintage fantasy map illustration of {subject}, pen and ink hand drawn "
                  "antique cartography symbol, dark sepia brown ink line art on plain solid "
                  "white background, centered, small, no text, no border, no shading, no colour")
        url = ("https://image.pollinations.ai/prompt/" + urllib.parse.quote(prompt)
               + f"?width={size}&height={size}&nologo=true&model=flux&seed={_seed(concept)}")
        try:
            req = urllib.request.Request(url, headers={"User-Agent": "onelife-map/1"})
            raw = urllib.request.urlopen(req, timeout=90).read()
            rgb = Image.open(io.BytesIO(raw)).convert("RGB")
        except Exception as e:
            print(f"  [icon] {concept}: AI fetch failed ({e}); using fallback")
    if rgb is None:
        rgb = procedural_icon(concept, size)
    os.makedirs(cache_dir, exist_ok=True)
    rgb.save(raw_path)
    return ink_from_white(rgb)


# --------------------------------------------------------------------------- #
#  Fonts
# --------------------------------------------------------------------------- #
def load_font(size, calligraphic=True):
    cands = ([r"C:\Windows\Fonts\Gabriola.ttf", r"C:\Windows\Fonts\GIL_____.TTF",
              r"C:\Windows\Fonts\georgiai.ttf", r"C:\Windows\Fonts\georgia.ttf"]
             if calligraphic else
             [r"C:\Windows\Fonts\georgia.ttf", r"C:\Windows\Fonts\times.ttf"])
    cands += ["/usr/share/fonts/truetype/dejavu/DejaVuSerif.ttf"]
    for p in cands:
        try:
            return ImageFont.truetype(p, size)
        except Exception:
            continue
    return ImageFont.load_default()


# --------------------------------------------------------------------------- #
#  Geometry helpers
# --------------------------------------------------------------------------- #
def wobble(p0, p1, amp, segs, seed):
    """A hand-drawn jittered polyline between two points (deterministic)."""
    rnd = _seed(seed)
    x0, y0 = p0; x1, y1 = p1
    dx, dy = x1 - x0, y1 - y0
    L = math.hypot(dx, dy) or 1
    nx, ny = -dy / L, dx / L
    pts = []
    for i in range(segs + 1):
        t = i / segs
        rnd = (rnd * 1103515245 + 12345) & 0x7FFFFFFF
        j = 0 if i in (0, segs) else (rnd / 0x7FFFFFFF - 0.5) * 2 * amp
        pts.append((x0 + dx * t + nx * j, y0 + dy * t + ny * j))
    return pts


# --------------------------------------------------------------------------- #
#  Layout
# --------------------------------------------------------------------------- #
def layout(data, W, H):
    cells = {c["id"]: c for c in data["cells"]}
    locs = data["locations"]
    nodes = data["nodes"]
    node_loc = {n["id"]: n.get("location") for n in nodes}

    gxs = [c["grid_x"] for c in cells.values()]
    gys = [c["grid_y"] for c in cells.values()]
    minx, maxx, miny, maxy = min(gxs), max(gxs), min(gys), max(gys)
    M = int(min(W, H) * 0.11)
    cols = (maxx - minx + 1); rows = (maxy - miny + 1)
    cw = (W - 2 * M) / cols; ch = (H - 2 * M) / rows

    def cell_center(c):
        return (M + (c["grid_x"] - minx + 0.5) * cw,
                M + (c["grid_y"] - miny + 0.5) * ch)

    # group locations by cell; hub at centre, the rest on concentric rings
    pos = {}
    home = {}
    by_cell = {}
    for l in locs:
        by_cell.setdefault(l.get("cell"), []).append(l)
    for cid, group in by_cell.items():
        c = cells.get(cid)
        if not c:
            continue
        ccx, ccy = cell_center(c)
        hub_loc = node_loc.get(c.get("arrival_node"))
        ring = [g for g in group if g["id"] != hub_loc]
        if hub_loc and any(g["id"] == hub_loc for g in group):
            pos[hub_loc] = [ccx, ccy]; home[hub_loc] = (ccx, ccy)
        r0, per = min(cw, ch) * 0.26, 6
        for i, g in enumerate(ring):
            rr, k = i // per, i % per
            cnt = min(per, len(ring) - rr * per)
            a = (k / max(1, cnt)) * 2 * math.pi - math.pi / 2 + rr * 0.5
            rad = r0 + rr * min(cw, ch) * 0.24
            pos[g["id"]] = [ccx + math.cos(a) * rad, ccy + math.sin(a) * rad * 0.85]
            home[g["id"]] = (ccx, ccy)
        if hub_loc not in pos and group:
            pos[group[0]["id"]] = [ccx, ccy]; home[group[0]["id"]] = (ccx, ccy)

    # relaxation: strong repulsion to avoid overlap + a gentle spring home so
    # each cell's places stay loosely in their region while spreading out.
    ids = list(pos)
    SEP = min(cw, ch) * 0.42
    for _ in range(300):
        for i in range(len(ids)):
            for j in range(i + 1, len(ids)):
                a, b = pos[ids[i]], pos[ids[j]]
                dx, dy = b[0] - a[0], b[1] - a[1]
                d = math.hypot(dx, dy) or 0.01
                if d < SEP:
                    push = (SEP - d) / 2
                    ux, uy = dx / d, dy / d
                    a[0] -= ux * push; a[1] -= uy * push
                    b[0] += ux * push; b[1] += uy * push
        for k in ids:
            p, (hx, hy) = pos[k], home[k]
            p[0] += (hx - p[0]) * 0.012; p[1] += (hy - p[1]) * 0.012
    for p in pos.values():
        p[0] = min(W - M * 0.55, max(M * 0.55, p[0]))
        p[1] = min(H - M * 0.55, max(M * 0.55, p[1]))

    # roads: cross-location story edges + inter-cell hub adjacency
    roads = []
    seen = set()
    for e in data["edges"] + [ed for n in nodes for ed in (n.get("edges") or [])
                              if isinstance(ed, dict)]:
        a = e.get("from"); b = e.get("to")
        # embedded edges have implicit `from` = their node; resolve via node_loc
        la = node_loc.get(a, a); lb = node_loc.get(b, b)
        if not la or not lb or la == lb or la not in pos or lb not in pos:
            continue
        key = tuple(sorted((la, lb)))
        if key in seen:
            continue
        seen.add(key)
        roads.append({"id": f"road-{la}--{lb}", "from": la, "to": lb,
                      "label": e.get("label", "")})
    for c1 in cells.values():
        for c2 in cells.values():
            if c1["id"] >= c2["id"]:
                continue
            if abs(c1["grid_x"] - c2["grid_x"]) + abs(c1["grid_y"] - c2["grid_y"]) == 1:
                l1 = node_loc.get(c1.get("arrival_node"))
                l2 = node_loc.get(c2.get("arrival_node"))
                if l1 in pos and l2 in pos and tuple(sorted((l1, l2))) not in seen:
                    seen.add(tuple(sorted((l1, l2))))
                    roads.append({"id": f"road-{l1}--{l2}", "from": l1, "to": l2,
                                  "label": "", "intercell": True})
    return cells, node_loc, pos, roads, M, cw, ch


# --------------------------------------------------------------------------- #
#  Rendering
# --------------------------------------------------------------------------- #
def parchment(W, H):
    base = Image.new("RGB", (W, H), PARCH)
    noise = Image.effect_noise((W, H), 22).convert("L")
    tint = Image.new("RGB", (W, H), PARCH_DARK)
    base = Image.composite(tint, base, noise.point(lambda v: int(v * 0.45)))
    # soft mottling
    blobs = Image.new("L", (W, H), 0)
    bd = ImageDraw.Draw(blobs)
    for i in range(40):
        r = _seed(f"blob{i}")
        x = r % W; y = (r // 7) % H; rad = 60 + (r % 240)
        bd.ellipse([x - rad, y - rad, x + rad, y + rad], fill=18)
    blobs = blobs.filter(ImageFilter.GaussianBlur(80))
    base = Image.composite(Image.new("RGB", (W, H), PARCH_DARK), base, blobs)
    # vignette
    vig = Image.new("L", (W, H), 0)
    vd = ImageDraw.Draw(vig)
    vd.rectangle([0, 0, W, H], fill=0)
    vd.ellipse([-W * 0.15, -H * 0.15, W * 1.15, H * 1.15], fill=255)
    vig = ImageOps.invert(vig.filter(ImageFilter.GaussianBlur(220)))
    base = Image.composite(Image.new("RGB", (W, H), (120, 96, 60)), base,
                           vig.point(lambda v: int(v * 0.5)))
    return base.convert("RGBA")


def terrain_patch(tile, concept, cx, cy, R):
    """Draw faint local terrain on a location tile, under the icon."""
    d = ImageDraw.Draw(tile, "RGBA")
    if concept in ("harbour",):
        d.ellipse([cx - R, cy + R*0.2, cx + R, cy + R*1.5], fill=WATER_INK + (70,))
        for k in range(3):
            yy = cy + R*0.6 + k*16
            d.arc([cx - R*0.7, yy-10, cx + R*0.7, yy+10], 200, 340, fill=INK_SOFT + (120,), width=3)
    elif concept in ("forest", "park"):
        d.ellipse([cx - R, cy - R*0.4, cx + R, cy + R], fill=FOREST + (60,))
    elif concept in ("lake",):
        d.ellipse([cx - R*0.9, cy + R*0.1, cx + R*0.9, cy + R], fill=WATER_INK + (70,))
    elif concept in ("village", "square", "estate", "house", "school"):
        d.ellipse([cx - R, cy - R*0.3, cx + R, cy + R], fill=FIELD + (50,))


def draw_label(tile, text, cx, y, font, max_w):
    d = ImageDraw.Draw(tile, "RGBA")
    # wrap to ~max_w
    words = text.split()
    lines, cur = [], ""
    for wd in words:
        t = (cur + " " + wd).strip()
        if d.textlength(t, font=font) <= max_w or not cur:
            cur = t
        else:
            lines.append(cur); cur = wd
    if cur:
        lines.append(cur)
    lh = font.getbbox("Ay")[3] + 6
    for i, ln in enumerate(lines):
        w = d.textlength(ln, font=font)
        yy = y + i * lh
        d.text((cx - w/2 + 2, yy + 2), ln, font=font, fill=(255, 250, 235, 130))  # paper highlight
        d.text((cx - w/2, yy), ln, font=font, fill=INK + (255,))


def render(content_dir, out_dir, use_ai, W, H):
    data = load_data(content_dir)
    cells, node_loc, pos, roads, M, cw, ch = layout(data, W, H)
    locs = {l["id"]: l for l in data["locations"]}
    os.makedirs(out_dir, exist_ok=True)
    cache = os.path.join(out_dir, "iconcache")

    label_font = load_font(int(min(cw, ch) * 0.058))
    title_font = load_font(int(H * 0.045))
    small_font = load_font(int(min(cw, ch) * 0.036), calligraphic=False)

    # icons per concept
    print("Generating icons (Pollinations pen-and-ink, cached)..." if use_ai
          else "Using procedural fallback icons...")
    icon_cache = {}
    for l in data["locations"]:
        cid, subj = concept_for(l)
        if cid not in icon_cache:
            icon_cache[cid] = get_icon(cid, subj, cache, use_ai)
    for extra, subj in (("compass", "an ornate cartographer compass rose with fleur-de-lis north"),
                        ("monster", "a coiling sea serpent monster"),
                        ("mountains", "a row of small hand drawn mountains"),):
        icon_cache[extra] = get_icon(extra, subj, cache, use_ai,
                                     size=520 if extra == "compass" else 360)

    meta = {"width": W, "height": H, "base": "base.jpg", "frame": "frame.png",
            "locations": [], "roads": [], "building": None, "legend": []}

    # ---- base (opaque bottom layer -> JPEG to keep it light for the browser) ----
    base = parchment(W, H)
    base.convert("RGB").save(os.path.join(out_dir, "base.jpg"), quality=82, optimize=True)

    # ---- roads (each its own tile) ----
    for r in roads:
        a = pos[r["from"]]; b = pos[r["to"]]
        pts = wobble(a, b, min(cw, ch) * 0.04, 14, r["id"])
        xs = [p[0] for p in pts]; ys = [p[1] for p in pts]
        pad = 30
        bx0, by0 = min(xs) - pad, min(ys) - pad
        bx1, by1 = max(xs) + pad, max(ys) + pad
        tw, th = int(bx1 - bx0), int(by1 - by0)
        tile = Image.new("RGBA", (tw, th), (0, 0, 0, 0))
        td = ImageDraw.Draw(tile, "RGBA")
        local = [(x - bx0, y - by0) for x, y in pts]
        dashed = r.get("intercell")
        width = 7 if r.get("intercell") else 5
        td.line(local, fill=INK_SOFT + (150,), width=width + 6, joint="curve")
        td.line(local, fill=INK + (230,), width=width, joint="curve")
        tile.save(os.path.join(out_dir, r["id"] + ".png"))
        meta["roads"].append({"id": r["id"], "from": r["from"], "to": r["to"],
                              "label": r.get("label", ""),
                              "tile": r["id"] + ".png", "bbox": [int(bx0), int(by0), tw, th],
                              "polygon": [[round(x, 1), round(y, 1)] for x, y in pts]})

    # ---- locations (skip the school location; it becomes a building) ----
    SCHOOL = "killebackskolan"
    school_nodes = [n for n in data["nodes"] if n.get("location") == SCHOOL]
    for l in data["locations"]:
        if l["id"] == SCHOOL and len(school_nodes) >= 3:
            continue
        cx, cy = pos[l["id"]]
        cid, _ = concept_for(l)
        T = int(min(cw, ch) * 0.46)
        tile = Image.new("RGBA", (T, T), (0, 0, 0, 0))
        lcx, lcy = T / 2, T * 0.42
        R = T * 0.3
        terrain_patch(tile, cid, lcx, lcy, R)
        icon = icon_cache[cid].resize((int(R * 1.8), int(R * 1.8)))
        tile.alpha_composite(icon, (int(lcx - R * 0.9), int(lcy - R * 0.9)))
        draw_label(tile, l.get("name") or l["id"], lcx, lcy + R * 1.0, label_font, T * 0.92)
        bx, by = int(cx - T / 2), int(cy - T / 2)
        tile.save(os.path.join(out_dir, f"loc-{l['id']}.png"))
        meta["locations"].append({
            "id": l["id"], "name": l.get("name") or l["id"], "cell": l.get("cell"),
            "x": round(cx, 1), "y": round(cy, 1), "concept": cid,
            "tile": f"loc-{l['id']}.png", "bbox": [bx, by, T, T],
            "reveal_nodes": [n["id"] for n in data["nodes"] if n.get("location") == l["id"]],
        })

    # ---- the school as a building of rooms ----
    if len(school_nodes) >= 3:
        cx, cy = pos[SCHOOL]
        cols = 3
        rowsN = math.ceil(len(school_nodes) / cols)
        room_w, room_h = int(min(cw, ch) * 0.34), int(min(cw, ch) * 0.2)
        bw = cols * room_w + 40
        bh = rowsN * room_h + 90
        bx0, by0 = int(cx - bw / 2), int(cy - bh / 2)
        # building shell tile
        shell = Image.new("RGBA", (bw, bh), (0, 0, 0, 0))
        sd = ImageDraw.Draw(shell, "RGBA")
        sd.rectangle([6, 50, bw - 6, bh - 6], fill=PARCH_DARK + (180,), outline=INK + (255,), width=6)
        sd.polygon([(0, 52), (bw / 2, 4), (bw, 52)], fill=PARCH + (220,), outline=INK + (255,))
        sd.text((bw / 2 - label_font.getlength("Killebäckskolan") / 2, bh - 44),
                "Killebäckskolan", font=label_font, fill=INK + (255,))
        shell.save(os.path.join(out_dir, "building-school.png"))
        rooms, doors = [], []
        room_xy = {}
        for i, n in enumerate(school_nodes):
            rc, rr = i % cols, i // cols
            rx = bx0 + 20 + rc * room_w + room_w / 2
            ry = by0 + 70 + rr * room_h + room_h / 2
            room_xy[n["id"]] = (rx, ry)
            rt = Image.new("RGBA", (room_w + 8, room_h + 8), (0, 0, 0, 0))
            rd = ImageDraw.Draw(rt, "RGBA")
            rd.rectangle([4, 4, room_w, room_h], outline=INK + (220,), width=4)
            nm = (n.get("title") or n["id"]).replace("kbk-", "")
            draw_label(rt, nm, (room_w + 8) / 2, room_h * 0.34, small_font, room_w * 0.92)
            rt.save(os.path.join(out_dir, f"room-{n['id']}.png"))
            rooms.append({"node_id": n["id"], "name": n.get("title") or n["id"],
                          "x": round(rx, 1), "y": round(ry, 1),
                          "tile": f"room-{n['id']}.png",
                          "bbox": [int(rx - (room_w + 8) / 2), int(ry - (room_h + 8) / 2),
                                   room_w + 8, room_h + 8]})
        # doors = edges among school nodes
        for n in school_nodes:
            for ed in (n.get("edges") or []):
                if isinstance(ed, dict) and node_loc.get(ed.get("to")) == SCHOOL and ed.get("to") in room_xy:
                    doors.append([n["id"], ed["to"]])
        meta["building"] = {"id": SCHOOL, "name": "Killebäckskolan",
                            "shell": "building-school.png",
                            "footprint": [bx0, by0, bw, bh],
                            "rooms": rooms, "doors": doors}
        meta["locations"].append({"id": SCHOOL, "name": "Killebäckskolan", "cell": "sandby",
                                  "x": round(cx, 1), "y": round(cy, 1), "concept": "school",
                                  "is_building": True, "tile": "building-school.png",
                                  "bbox": [bx0, by0, bw, bh],
                                  "reveal_nodes": [n["id"] for n in school_nodes]})

    # ---- frame: border, compass, title, legend ----
    frame = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    fd = ImageDraw.Draw(frame, "RGBA")
    for off, wd in ((M * 0.45, 8), (M * 0.55, 3)):
        fd.rectangle([off, off, W - off, H - off], outline=INK + (255,), width=int(wd))
    # compass (top-right)
    comp = icon_cache.get("compass")
    if comp:
        cs = int(min(cw, ch) * 0.5)
        frame.alpha_composite(comp.resize((cs, cs)), (int(W - M * 0.6 - cs), int(M * 0.6)))
    # sea monster (bottom area, near Malmö/water)
    mon = icon_cache.get("monster")
    if mon:
        ms = int(min(cw, ch) * 0.5)
        frame.alpha_composite(mon.resize((ms, ms)), (int(M * 0.7), int(H - M * 0.7 - ms)))
    # title cartouche
    title = "Karta över Skåne  ·  Anno 1992"
    tw = title_font.getlength(title)
    tx, ty = W / 2 - tw / 2, M * 0.5
    fd.rounded_rectangle([tx - 40, ty - 14, tx + tw + 40, ty + title_font.size + 18],
                         radius=18, fill=PARCH + (235,), outline=INK + (255,), width=4)
    fd.text((tx, ty), title, font=title_font, fill=INK + (255,))
    # legend (bottom-right)
    legend_items = [("school", "School / building"), ("church", "Church"),
                    ("harbour", "Harbour & sea"), ("forest", "Woods"),
                    ("castle", "Castle"), ("cemetery", "Cemetery"),
                    ("station", "Station"), ("village", "Village / town")]
    lx, ly = int(W - M * 0.6 - cw * 0.9), int(H - M * 0.6 - ch * 0.95)
    lw, lh = int(cw * 0.9), int(ch * 0.95)
    fd.rounded_rectangle([lx, ly, lx + lw, ly + lh], radius=16,
                         fill=PARCH + (228,), outline=INK + (255,), width=4)
    fd.text((lx + 24, ly + 14), "Legend", font=load_font(int(lh * 0.11)), fill=INK + (255,))
    row = ly + int(lh * 0.2)
    step = int((lh - lh * 0.2) / len(legend_items))
    isz = int(step * 0.78)
    for cid, name in legend_items:
        ic = icon_cache.get(cid)
        if ic:
            frame.alpha_composite(ic.resize((isz, isz)), (int(lx + 22), int(row)))
        fd.text((lx + 28 + isz, row + isz * 0.3), name, font=small_font, fill=INK + (255,))
        meta["legend"].append({"concept": cid, "label": name})
        row += step
    frame.save(os.path.join(out_dir, "frame.png"))

    with open(os.path.join(out_dir, "world-map.meta.json"), "w", encoding="utf-8") as fh:
        json.dump(meta, fh, ensure_ascii=False, indent=2)

    # a flattened preview for eyeballing
    preview = base.copy()
    for r in meta["roads"]:
        t = Image.open(os.path.join(out_dir, r["tile"])); preview.alpha_composite(t, (r["bbox"][0], r["bbox"][1]))
    for l in meta["locations"]:
        t = Image.open(os.path.join(out_dir, l["tile"])); preview.alpha_composite(t, (l["bbox"][0], l["bbox"][1]))
    if meta["building"]:
        for rm in meta["building"]["rooms"]:
            t = Image.open(os.path.join(out_dir, rm["tile"])); preview.alpha_composite(t, (rm["bbox"][0], rm["bbox"][1]))
    preview.alpha_composite(frame, (0, 0))
    preview.convert("RGB").save(os.path.join(out_dir, "preview.png"))

    print(f"Wrote {len(meta['locations'])} locations, {len(meta['roads'])} roads "
          f"to {out_dir}\n  open {os.path.join(out_dir, 'preview.png')} to eyeball it.")


def main():
    ap = argparse.ArgumentParser(description="Render the OneLife world map.")
    ap.add_argument("--content", help="game-data dir")
    ap.add_argument("--out", default=os.path.join(HERE, "..", "..", "..", "web", "public", "worldmap"))
    ap.add_argument("--no-ai", action="store_true", help="procedural icons only (offline)")
    ap.add_argument("--size", default="3200x2400", help="canvas WxH")
    a = ap.parse_args()
    W, H = (int(v) for v in a.size.lower().split("x"))
    content = find_content_dir(a.content)
    out = os.path.abspath(a.out)
    print(f"content: {content}\nout:     {out}")
    render(content, out, not a.no_ai, W, H)


if __name__ == "__main__":
    main()
